### ISSUE TITLE
Random behaviour of generated .c inference file

### ISSUE THREAD

**Issue by elias-Mimetrik** [f0uriest/keras2c#11]
Hello. I am creating a simple network of around 10 layers composed of convolutions and max pooling, ending with a dense layer. The input is an array of a few thousand values, the output is an array of a small number of values (e.g. 10).

I can convert the network successfully to .C using this library. But when inferring the C files, the code behaves randomly. Sometimes it gives the expected 10 value result, sometimes it gives a `Segmentation fault (core dumped)` error. If I run the resulting executable consecutively, it might produce an output, or it might give the segmentation error.

Any ideas please? I can post the code if needed.. Thank you.

**Comment by orestonce** [comment]
Can you paste the model file 、sample input  and expected output ?
