### ISSUE TITLE
Fail to generate c code from model using the test example

### ISSUE THREAD

**Issue by newfrogg** [f0uriest/keras2c#20]
Hi there, I encountered with crashing problems when trying to generating c code from model.h5 in the example. Here is the output:
![image](https://github.com/f0uriest/keras2c/assets/85973867/436b63f1-b852-4e0c-a11c-001b0a0ec4d2)
**I use the numpy 1.26.0 and tensorflow 2.16.1 for python 3.10.12.**

 Any help would be greatly appreciated. This issue appears accidently that I might think It wouldn't be. Thanks.

**Comment by jnulzl** [comment]
@newfrogg Hi, tensorflow downgrade to 2.15.1 can be solved!
