### ISSUE TITLE
Test returns large absolute error

### ISSUE THREAD

**Issue by gwiesenekker** [f0uriest/keras2c#9]
Hi,

I have been testing keras2c on a network, but the test returns a large absolute error. What could be the problem? I have attached the H5 model.

[gwd_model.zip](https://github.com/f0uriest/keras2c/files/8027663/gwd_model.zip)

Regards,
GW

**Comment by gwiesenekker** [comment]
I have attached a smaller model that is perhaps easier to troubleshoot.
[gwd_model_small.zip](https://github.com/f0uriest/keras2c/files/8027770/gwd_model_small.zip)

Regards,
GW

**Comment by gwiesenekker** [comment]
I have attached an even smaller model that is perhaps even easier to troubleshoot.
[gwd_model_smaller.zip](https://github.com/f0uriest/keras2c/files/8027818/gwd_model_smaller.zip)

Regards,
GW

**Comment by f0uriest** [comment]
Sorry for the delayed response. I took a look and it looks like the C code is generating the correct outputs, but the reference values from python were wrong. Your model is expecting the input type int64, while keras2c currently only works for floating point inputs. To generate the testing data it was casting floats to ints in python but not in C and that seems to be the problem. If you change the input dtype of the model to float it seems to work fine, and you would just need to cast your inputs to float before inference. Let me know if you have any more trouble.
